### PR TITLE
opendingux: gcw0: Add libfluidsynth package with symlink

### PR DESCRIPTION
**Pull request by EhotPotaskun**
Resolving ScummVM dependency

Signed-off-by: Egor Yakovlev <ehot.potaskun@gmail.com>

### CODE REVIEW

**Comment by mthuurne** [comment]
If two libraries have different SONAME values, that typically means they are not compatible. So a symlink from one version to the other is likely not going to work for all possible users of fluidsynth. Or is there a reason to assume that in this case the newer library is fully binary compatible with the older one?

Originally we had a goal of keeping the same SONAMEs in the OpenDingux rootfs across releases, but I don't know if that's still feasible across a time span of 10 years. @pcercuei: what is the compatibility policy that you're using at the moment?

**Comment by pcercuei** [comment]
@mthuurne I'm fine with a symlink as long as it works with the few apps we have that use it, and from what I've seen, they do.

@EhotPotaskun better symlink to libfluidsynth.so.2, or it will break at the next minor version update.

**Comment by EhotPotaskun** [comment]
@pcercuei thanks for suggestion, fixed

**Comment by pcercuei** [comment]
@EhotPotaskun could you also split the symlink change and config change into two separate commits? please :)

**Comment by EhotPotaskun** [comment]
@pcercuei Ok, here it is

**Comment by pcercuei** [comment]
Merged, thanks!

**Pull request merged**
