### PR TITLE
changed `$()` to backticks in target scripts.

### PR DESCRIPTION
**Pull request by aeromaxx**

### CODE REVIEW

**Comment by a-dekker** [comment]
Why would you want to change this? http://mywiki.wooledge.org/BashFAQ/082

Edit: I see there already was a discussion over here: https://github.com/OpenDingux/buildroot/pull/82
I do not think $() is a bash-ism as @pcercuei states here https://github.com/OpenDingux/buildroot/pull/82#issuecomment-1282257090. It is POSIX standard and works in any relevant shell, including on opendingux. The use of backticks is really discouraged nowadays.

**Comment by pcercuei** [comment]
Yeah, I'm not too keen on merging this change. It touches a lot of lines, so not only it may introduce regressions, it also pollutes the "git blame" history.

**Comment by a-dekker** [comment]
As I don't agree on your stands on the back-tick use, I do agree about your view on the git history pollution. Standards should be set on a start of a project, making large formatting/linting changes during a project makes tracing/bisecting beyond that point a pain.

**Comment by aeromaxx** [comment]
> Yeah, I'm not too keen on merging this change. It touches a lot of lines, so not only it may introduce regressions, it also pollutes the "git blame" history.

I did what you asked I thought? https://github.com/OpenDingux/buildroot/pull/82#issuecomment-1282472092

I was wanting to help/contribute to the project, but seems I have just wasted my time.

**Comment by pcercuei** [comment]
Yes, I thought `$()` was a bash-ism and not POSIX. Sorry about that.

Reading @a-dekker's link, I guess it's better to use these than backticks.

Looking at your original PR converting backticks to `$()`, it touched many less files within board/opendingux/ than this PR does.

So if you take your old commit 2f0f0d6ccf00b5dd47f7e04e0b4694727df89de3 and only stage OpenDingux-specific files the resulting commit should be small enough that it's okay to merge.

**Pull request closed without merging**
