### PR TITLE
Add DroidSansFallback.ttf font to skeleton

### PR DESCRIPTION
**Pull request by glebm**
This is a CJK font at 3.3 MiB
Being a fallback font, it *only* has CJK characters

This font is used as the default fallback font on Ubuntu
(https://packages.ubuntu.com/focal/fonts/fonts-droid-fallback)

Font information:
* Source: https://android.googlesource.com/platform/frameworks/base/
* Copyright: Copyright © 2006, 2007, 2008, 2009, 2010 Google Corp.
             Droid is a trademark of Google Corp.
* License: Apache-2

Latest version from:
https://android.googlesource.com/platform/frameworks/base/+/2d8961d99f3aa559dbd4b78b716ab36c456b43e1

### CODE REVIEW

**Comment by glebm** [comment]
@pcercuei Thoughts? I'd like every distibution to have a CJK font so that apps can have CJK support without bundling a heavy font.

This is the smallest CJK font I could find. It's not perfect (e.g. it's a few years old so it doesn't have ㋿) but it's very small for a CJK fallback font.

**Comment by pcercuei** [comment]
Need your signature on the commit (```git commit --amend -s```).

**Comment by glebm** [comment]
Done

**Comment by pcercuei** [comment]
Please include the NOTICE file alongside the font, as required in the license (paragraph 4.d).

**Comment by glebm** [comment]
I'm happy to include it though I thought this wouldn't count as a "Derivative Work" (paragraph 4.d only applies to derivative works):

> For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.

I've checked a few Linux distributions for the NOTICE file, and they don't have one:

* https://packages.ubuntu.com/groovy/all/fonts-droid-fallback/filelist
* https://packages.debian.org/buster/all/fonts-droid-fallback/filelist
* https://www.archlinux.org/packages/community/any/ttf-droid/

GhostScript does include a file called `DroidSansFallback.NOTICE`:

* http://git.ghostscript.com/?p=ghostpdl.git;a=tree

I think calling it just `NOTICE` might be confusing, `DroidSansFallback.NOTICE` seems better.

Should I place it next to the font or in the root of the repository?

**Comment by pcercuei** [comment]
Just NOTICE in the font's directory, then it's not ambiguous.

**Comment by glebm** [comment]
Done!

**Comment by glebm** [comment]
Closed in favor of https://github.com/OpenDingux/buildroot/pull/29

**Pull request closed without merging**
