### PR TITLE
package/libmodplug: Add a patch fixing cctype UB

### LINKED ISSUE #105: Playing mod music files often results in a crash
Playing mod music files is largely broken on OD-beta. And it got even worse in the latest releases of OD-beta, some games with mod music that did work a few releases earlier now also crash. some people resort to including their self compiled library files (https://github.com/plrguez/hurrican-od/blob/main/Hurrican/build_libmodplug.sh for example) if possible, but that's an unwanted workaround if you ask me.
Any chance this could be addressed?

### PR DESCRIPTION
**Pull request by glebm**
Also sent upstream https://github.com/Konstanty/libmodplug/pull/92

Fixes #105

### CODE REVIEW

**Comment by glebm** [comment]
Upstream buildroot now also uses the git version of libmodplug as of https://github.com/buildroot/buildroot/commit/369ff9a88ff8e88b78287e37fbaf191e57598be2

Will send them this patch also

**Comment by glebm** [comment]
Sent the patch to buildroot https://patchwork.ozlabs.org/project/buildroot/patch/20230109220041.33943-1-glex.spb@gmail.com/

**Comment by pcercuei** [comment]
Looks like neither upstream libmodplug nor buildroot are very interested in the patch.

Could you move it to `board/opendingux/patches/libmodplug`, so that it doesn't cause merge issues if it's eventually accepted upstream?

**Comment by glebm** [comment]
Done in #122 (also added the patches that fix unaligned reads)

**Pull request closed without merging**
