### PR TITLE
od-passwd-config: Fix icon

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by pcercuei** [comment]
And where is that passwd.png?

**Comment by glebm** [comment]
Here:

https://github.com/OpenDingux/buildroot/blob/4b37c62e2e27ac68e7ea67b3f5bd9c6bd8df62ad/board/opendingux/package/od-passwd-config/od-passwd-config.mk#L17

Though I haven't tested this fix

**Comment by pcercuei** [comment]
Right - missed it, I was looking in gmenu2x' data folder.

Could you sign the commit, so that I can merge it?

**Comment by glebm** [comment]
Signed

**Pull request merged**
