### PR TITLE
Changed some of the bash shell scripts to make them consistent

### PR DESCRIPTION
**Pull request by aeromaxx**
* Indentation was inconsistent across files, and sometimes in the same files, both spaces and tabs used
	* Changed all indentation to use tabs to make it consistent
* Formatting was inconsistent across files, double spaces between command and \, double spaces between command and |
	* Changed all double spaces to a single space to make it consistent
* Formatting was inconsistent across files, single space between ] and ;
	* Removed the space to make it consistent
* The use of backticks and subshells $( ) was inconsistent across files, and sometimes in the same files, both were used
	* Changed all backticks to subshells $( )

### CODE REVIEW

**Comment by pcercuei** [comment]
You change a lot of stuff that's completely unrelated to OpenDingux.

If those changes really make sense, which I doubt, you will need to send them as patches to the Buildroot project directly.

As for the changes that touch OpenDingux specific files, the majority should be dropped. For instance, $() is a bash-ism and using backquotes is actually correct.

**Comment by aeromaxx** [comment]
There is inconsistency between the files some use `$()` and some use backticks, why not have some consistency instead of some using backticks and some using `$()`, I think there was even some inconsistency within the same file using both `$()` and backticks.

From `man bash`:

```
Command substitution allows the output of a command to replace the command name. There are two forms:

          $(command)
   or
          `command`
```

Also, ` `` ` are more difficult to handle, you cannot nest them for example. See comments below and also [Why is $(...) preferred over ... (backticks)?](http://mywiki.wooledge.org/BashFAQ/082).

**Comment by pcercuei** [comment]
@aeromaxx you can send a PR to change the `$()` to backticks on OD files.

Note that `$()` are fine on the build-system scripts, we just don't want them in target scripts.

**Comment by aeromaxx** [comment]
@pcercuei So which files do you deem to be OD specific? Also I am not entirely sure which are target scripts and which are build scripts.

Can I include a PR to sort out the indentation also maybe? spaces or tabs, that's inconsistent also.

**Comment by pcercuei** [comment]
OD-specific files are in `board/opendingux/`.

Target scripts are in `board/opendingux/target_skeleton/` and `board/opendingux/{gcw0,lepus,rs90}/overlay/`

I don't really want commits that fix indentation, unless it's only a small number of lines. Otherwise such changes will trash the git history.

**Comment by aeromaxx** [comment]
Ah I see ok, gotcha.

I will have a look at the files mentioned in the directories above and fix the backticks and `$()` to make them consistent, and do a PR for that, and just wait for it to be reviewed/accepted/closed or whatever.

Then do a separate pull request for the indentation so that you can review that separately.

**Pull request closed without merging**
