### PR TITLE
opendingux: gcw0: Add BR2_PACKAGE_BOOST_PROGRAM_OPTIONS

### PR DESCRIPTION
**Pull request by glebm**
Fixes blockattack.opk startup error (still doesn't work but now for other reasons).

Signed-off-by: Gleb Mazovetskiy <glex.spb@gmail.com>

### CODE REVIEW

**Comment by pcercuei** [comment]
I am not willing to include Boost, unless we can find a way to have them static only. Boost breaks ABI at *every* release which would be a nightmare with dynamic libs.

**Comment by glebm** [comment]
@pcercuei Can you help me change the BlockAttack build to link Boost statically?

https://github.com/od-contrib/opks/blob/master/package/blockattack/blockattack.mk

**Comment by glebm** [comment]
Looks like boost should install both static and shared libs unless `BR2_STATIC/SHARED_LIBS=y`. I'll look into this a bit more.

**Comment by glebm** [comment]
There is no way to configure this for just boost but selecting `BR2_SHARED_STATIC_LIBS=y` in defconfig and adding `-DBoost_USE_STATIC_LIBS=ON` to `BLOCKATTACK_CONF_OPTS` does make this work

**Pull request closed without merging**
