### PR TITLE
Update linux and configs

### PR DESCRIPTION
**Pull request by glebm**
1. We enable `CONFIG_EMBEDDED`, which selects `CONFIG_EXPERT`.

   `CONFIG_EXPERT` selects `CONFIG_DEBUG_KERNEL`, which enables several kernel debugging options by default.

   This commit disables them.

   I also considered disabling `CONFIG_EMBEDDED` instead because we do not use it for anything.
   However, we do need `CONFIG_EXPERT` (selected by `EMBEDDED`) for `LD_DEAD_CODE_DATA_ELIMINATION` anyway, and `CONFIG_EXPERT` is the one that actually selects `DEBUG_KERNEL`.

   rg99 comparison (`dmesg | grep Memory`):

   ```
   - Memory: 23616K/32768K available (4150K kernel code, 610K rwdata, 604K rodata, 1216K init, 274K bss, 7104K reserved, 2048K cma-reserved)
   + Memory: 23664K/32768K available (4126K kernel code, 606K rwdata, 600K rodata, 1248K init, 238K bss, 7056K reserved, 2048K cma-reserved)
   ```

2. Updates the kernel version and sets `CONFIG_INET_TABLE_PERTURB_ORDER=8` on the rs90.

### CODE REVIEW

**Comment by pcercuei** [comment]
I think it would be better to keep `CONFIG_DEBUG_BUGVERBOSE`, at least for gcw0 and lepus. The rest can go.

**Comment by glebm** [comment]
Done. Also removed the duplicate `CONFIG_DEBUG_MISC is not set` from the rs90 config.
Keeping `CONFIG_DEBUG_BUGVERBOSE is not set` for the rs90 only because it's a lot of code/data.

**Comment by pcercuei** [comment]
What's with the kernel bump?

**Comment by glebm** [comment]
> What's with the kernel bump?

To include https://github.com/OpenDingux/linux/commit/b4f1012843697d3b2b8d12113a79f0c3dfe6485d
It is the only new commit in the jz-6.1 branch

**Comment by pcercuei** [comment]
@glebm Please add a small description about why you're bumping the kernel version then.

**Comment by glebm** [comment]
Added description to the commit

**Pull request merged**
