### PR TITLE
od: system_info improvements

### PR DESCRIPTION
**Pull request by glebm**
1. Print kernel and rootfs date in the same format.
2. Print device model.
3. Print CPU frequency.
4. Print MemAvailable.

Example output from an rg99:

```
Kernel version: 6.1.0-rc4-opendingux
Compiled: Nov 21 13:24:37 2022

Root FS version: g8050d35c9f-dirty
Compiled: Nov 21 13:24:57 2022

Device: ylm,rg99
CPU: JZ4725B @ 360 MHz
RAM: 26960 kB usable, 6736 kB available
Swap: 	/dev/zram0: 21488 kB

Network interfaces:
   usb0 10.1.1.3
```

### CODE REVIEW

**Comment by pcercuei** [comment]
For getting the device name, it would be better to do: `MODEL=$(grep machine /proc/cpuinfo |sed 's/.*: //')`

This would print e.g. "GCW Zero" instead of "gcw,zero". Unless the "DT-compatible" name is really what you want to show.

**Comment by glebm** [comment]
Sounds good, let's show both, it's helpful when diagnosing issues

**Comment by pcercuei** [comment]
You could print `${MODEL} (${DT_DEV})` e.g. `Anbernic RG-350 (ylm,rg350)`

**Comment by glebm** [comment]
Done!

**Comment by glebm** [comment]
"usable" is basically the best approximation to "free", perhaps we should just say "free"?

**Comment by glebm** [comment]
Changed "available" to "free"

**Comment by pcercuei** [comment]
@glebm I'd be in favor of removing the display of "free" memory. It has absolutely no value and is misleading, as it only represents the amount of RAM that is not being used right now. So it can fluctuate a lot, depending on the amount of cache used, and it doesn't mean that your program cannot use more than this value.

**Comment by glebm** [comment]
From https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773, it does not look like "MemAvailable" depends on the amount of cache used

It is an estimate of how much memory is available for starting new applications without swapping

We measure it with only system_info itself running, so it should be pretty close to the real "free" RAM

**Comment by pcercuei** [comment]
@glebm but it fluctuates awfully. Sometimes I get 9 MiB "free", sometimes 15 MiB.

**Comment by glebm** [comment]
I've only ever seen around 9 MiB (with 16 KiB page size), if it fluctuates that much then yeah but I haven't been able to reproduce that

**Pull request merged**
