### PR TITLE
opendingux: Add fluidsynth1 package for backwards compatibility

### PR DESCRIPTION
**Pull request by glebm**
Backwards compatibility with existing OPKs, such as PrBoom+

### CODE REVIEW

**Comment by pcercuei** [comment]
Is a symlink from libfluidsynth.so.2 to libfluidsynth.so.1 enough to make OPKs work?

**Comment by glebm** [comment]
IIRC I had tried that but no, the API changed a lot between versions

**Comment by pcercuei** [comment]
I just tried that, at least with ScummVM it's possible to run with a symlink. What did you try?

**Comment by glebm** [comment]
IIRC the one I tried was PrBoom+

However, there is now a release of that for OD beta

https://github.com/Ninoh-FOX/PrBoom-plus-for-RG350/releases

**Comment by pcercuei** [comment]
I merged #49, if it turns out a symlink isn't enough (so far it looks OK), I will re-open this PR. Thanks anyway.

**Pull request closed without merging**
