### PR TITLE
od: Add od-model binary

### PR DESCRIPTION
**Pull request by glebm**
This tiny binary replaces the sed incantation used in scripts to obtain the model from sysfs.

It is more convenient, robust, and faster than the sed command.

`time` measurement:

```shell
$ time /usr/sbin/od-model
ylm,rg99
0.00user 0.00system 0:00.01elapsed 44%CPU (0avgtext+0avgdata 672maxresident)k
0inputs+0outputs (0major+25minor)pagefaults 0swaps
$ time sed -n 's/\(.*\)ingenic.*/\1/p' /sys/firmware/devicetree/base/compatible
ylm,rg990.00user 0.02system 0:00.03elapsed 69%CPU (0avgtext+0avgdata 880maxresident)k
0inputs+0outputs (0major+52minor)pagefaults 0swaps
```

### CODE REVIEW

**Comment by pcercuei** [comment]
So we gain 0.02 seconds, yay?

**Comment by glebm** [comment]
It correctly splits on `\0` (instead of stripping `ingenic.*`), `/usr/sbin/od-model` is easier to read than the sed command, and it saves 0.06 seconds because we call it 3 times

**Comment by pcercuei** [comment]
So we gain 0.06 seconds, yay?

Why not simply move the sed command into a script named `od-model`?

**Comment by glebm** [comment]
It correctly splits on \0 (instead of stripping `ingenic.*`, which is a hack)

**Comment by glebm** [comment]
The splitting could probably be implemented via `IFS= read -r -d $'\0'` but if you do that, might as well do it in C, no?

**Comment by glebm** [comment]
Like this:
```sh
IFS= read -r -d $'\0' MODEL < /sys/firmware/devicetree/base/compatible
```

**Comment by glebm** [comment]
I'll do that in a separate PR, it's both more readable than sed and correct

**Comment by glebm** [comment]
Sent https://github.com/OpenDingux/buildroot/pull/97

**Pull request closed without merging**
